/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppSelfystic {}
  interface AppSelfysticAttributes extends StencilHTMLAttributes {}

  interface AppSelfyCapture {}
  interface AppSelfyCaptureAttributes extends StencilHTMLAttributes {}

  interface AppSelfyCardList {}
  interface AppSelfyCardListAttributes extends StencilHTMLAttributes {}

  interface AppSelfyCardDefault {
    'title': string;
  }
  interface AppSelfyCardDefaultAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface AppSelfyCard {
    'model': any;
  }
  interface AppSelfyCardAttributes extends StencilHTMLAttributes {
    'model'?: any;
    'onLiked'?: (event: CustomEvent) => void;
    'onShared'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppSelfystic': Components.AppSelfystic;
    'AppSelfyCapture': Components.AppSelfyCapture;
    'AppSelfyCardList': Components.AppSelfyCardList;
    'AppSelfyCardDefault': Components.AppSelfyCardDefault;
    'AppSelfyCard': Components.AppSelfyCard;
  }

  interface StencilIntrinsicElements {
    'app-selfystic': Components.AppSelfysticAttributes;
    'app-selfy-capture': Components.AppSelfyCaptureAttributes;
    'app-selfy-card-list': Components.AppSelfyCardListAttributes;
    'app-selfy-card-default': Components.AppSelfyCardDefaultAttributes;
    'app-selfy-card': Components.AppSelfyCardAttributes;
  }


  interface HTMLAppSelfysticElement extends Components.AppSelfystic, HTMLStencilElement {}
  var HTMLAppSelfysticElement: {
    prototype: HTMLAppSelfysticElement;
    new (): HTMLAppSelfysticElement;
  };

  interface HTMLAppSelfyCaptureElement extends Components.AppSelfyCapture, HTMLStencilElement {}
  var HTMLAppSelfyCaptureElement: {
    prototype: HTMLAppSelfyCaptureElement;
    new (): HTMLAppSelfyCaptureElement;
  };

  interface HTMLAppSelfyCardListElement extends Components.AppSelfyCardList, HTMLStencilElement {}
  var HTMLAppSelfyCardListElement: {
    prototype: HTMLAppSelfyCardListElement;
    new (): HTMLAppSelfyCardListElement;
  };

  interface HTMLAppSelfyCardDefaultElement extends Components.AppSelfyCardDefault, HTMLStencilElement {}
  var HTMLAppSelfyCardDefaultElement: {
    prototype: HTMLAppSelfyCardDefaultElement;
    new (): HTMLAppSelfyCardDefaultElement;
  };

  interface HTMLAppSelfyCardElement extends Components.AppSelfyCard, HTMLStencilElement {}
  var HTMLAppSelfyCardElement: {
    prototype: HTMLAppSelfyCardElement;
    new (): HTMLAppSelfyCardElement;
  };

  interface HTMLElementTagNameMap {
    'app-selfystic': HTMLAppSelfysticElement
    'app-selfy-capture': HTMLAppSelfyCaptureElement
    'app-selfy-card-list': HTMLAppSelfyCardListElement
    'app-selfy-card-default': HTMLAppSelfyCardDefaultElement
    'app-selfy-card': HTMLAppSelfyCardElement
  }

  interface ElementTagNameMap {
    'app-selfystic': HTMLAppSelfysticElement;
    'app-selfy-capture': HTMLAppSelfyCaptureElement;
    'app-selfy-card-list': HTMLAppSelfyCardListElement;
    'app-selfy-card-default': HTMLAppSelfyCardDefaultElement;
    'app-selfy-card': HTMLAppSelfyCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
